# Generated by Django 2.2 on 2020-07-19 13:55

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', tinymce.models.HTMLField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.Profile')),
                ('comments', models.ManyToManyField(blank=True, to='actions.Comment')),
                ('likes', models.ManyToManyField(blank=True, to='actions.Like')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
