# Generated by Django 2.2 on 2020-07-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='followers_id',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='user_id',
            new_name='user',
        ),
    ]
