# Generated by Django 2.2 on 2020-06-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='madia/None/no-img.jpg', upload_to='media/'),
        ),
    ]
