# Generated by Django 2.0 on 2020-06-25 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20200625_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='is_like',
            field=models.BooleanField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
