# Generated by Django 2.0 on 2020-06-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_like_is_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, to='feed.Like'),
        ),
    ]
